export enum ErrorCode {
  // Email errors
  EMAIL_INVALID_FORMAT = 'EMAIL_INVALID_FORMAT',
  EMAIL_SENDING_FAILED = 'EMAIL_SENDING_FAILED',
  EMAIL_SERVICE_NOT_CONFIGURED = 'EMAIL_SERVICE_NOT_CONFIGURED',
  EMAIL_AUTH_FAILED = 'EMAIL_AUTH_FAILED',
  EMAIL_CONNECTION_FAILED = 'EMAIL_CONNECTION_FAILED',
  EMAIL_TIMEOUT = 'EMAIL_TIMEOUT',
  EMAIL_RECIPIENT_REJECTED = 'EMAIL_RECIPIENT_REJECTED',
  EMAIL_POLICY_REJECTION = 'EMAIL_POLICY_REJECTION',

  // Registration errors
  REGISTRATION_EMAIL_EXISTS = 'REGISTRATION_EMAIL_EXISTS',
  REGISTRATION_USERNAME_EXISTS = 'REGISTRATION_USERNAME_EXISTS',
  REGISTRATION_DATA_NOT_FOUND = 'REGISTRATION_DATA_NOT_FOUND',
  REGISTRATION_CODE_INVALID = 'REGISTRATION_CODE_INVALID',
  REGISTRATION_CODE_EXPIRED = 'REGISTRATION_CODE_EXPIRED',
  REGISTRATION_MAX_ATTEMPTS = 'REGISTRATION_MAX_ATTEMPTS',

  //  Auth errors
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',

  // Validation errors
  VALIDATION_EMAIL_REQUIRED = 'VALIDATION_EMAIL_REQUIRED',
  VALIDATION_USERNAME_REQUIRED = 'VALIDATION_USERNAME_REQUIRED',
  VALIDATION_USERNAME_LENGTH = 'VALIDATION_USERNAME_LENGTH',
  VALIDATION_USERNAME_PATTERN = 'VALIDATION_USERNAME_PATTERN',
  VALIDATION_PASSWORD_REQUIRED = 'VALIDATION_PASSWORD_REQUIRED',
  VALIDATION_PASSWORD_LENGTH = 'VALIDATION_PASSWORD_LENGTH',
  VALIDATION_PASSWORD_NOT_MATCH = 'VALIDATION_PASSWORD_NOT_MATCH',
  VALIDATION_CODE_REQUIRED = 'VALIDATION_CODE_REQUIRED',
  VALIDATION_CODE_FORMAT = 'VALIDATION_CODE_FORMAT',
  VALIDATION_TEMP_USER_ID_REQUIRED = 'VALIDATION_TEMP_USER_ID_REQUIRED',

  // Server errors
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  // Password reset errors
  PASSWORD_RESET_DATA_NOT_FOUND = 'PASSWORD_RESET_DATA_NOT_FOUND',
  PASSWORD_RESET_MAX_ATTEMPTS = 'PASSWORD_RESET_MAX_ATTEMPTS',
  PASSWORD_RESET_CODE_INVALID = 'PASSWORD_RESET_CODE_INVALID',
  PASSWORD_RESET_CODE_EXPIRED = 'PASSWORD_RESET_CODE_EXPIRED',
  PASSWORD_RESET_CREDENTIALS = 'PASSWORD_RESET_CREDENTIALS',

  // Hack errors
  GO_FUCK_YOURSELF = 'GO_FUCK_YOURSELF',
}

export interface ErrorResponse {
  statusCode: number;
  message: string;
  errorCode: ErrorCode;
  details?: any;
}
